### ISSUE TITLE
odd staticmethod that is also private in Project

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-lib#16]
I have encountered this piece of code:

```python
@staticmethod
def _sort_leaderboard_columns(column_names):
```

in [here](https://github.com/neptune-ml/neptune-lib/blob/master/neptunelib/project.py#L164-L165).

Also:

```python
@staticmethod
def _simple_dict_to_dataframe(d):
```
in [here](https://github.com/neptune-ml/neptune-lib/blob/master/neptunelib/experiment.py#L148-L149)
I think it is possibly a typo. 

It seems odd to have a staticmethod that we want to show to the world as Projects.sort_leaderboard_columns but at the same time it is private so we don't.  
I would go with either private or static or even a simple helper function.

**Comment by pitercl** [comment]
It's a helper method, it's not a part of the API of this class. The only reason it's static is that it doesn't use `self`. I'm not aware of any guidelines that discourage private static methods.

**Comment by jakubczakon** [comment]
Ok, in this case what is the benefit of using staticmethod vs simple private function? 

It is curiosity/ignorance than anything else on my part.

**Comment by pitercl** [comment]
The only benefit is that IMO the code is more readable when there are no unused variables:
```py
def _sort_leaderboard_columns(self, column_names):
   ...
```
In this case `self` would be unused and my IDE would protest against it.

**Comment by jakubczakon** [comment]
I was thinking private function, not private method.
Simply:

```python
def _sort_leaderboard_columns(column_names):
...
```

**Comment by pitercl** [comment]
Oh, sorry for the misunderstanding. In that case there's no real benefit. If you prefer a private function, I'm completely fine with it.

**Comment by jakubczakon** [comment]
Thanks @pitercl! 
I will leave it as is, just wanted to know.
