### ISSUE TITLE
Simplify Session/Credentials 

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-lib#4]
It seems reasonable to simplify the api by passing `NEPTUNE_API_TOKEN` directly into the Session object and create Credentials object inside of that class:

```python
import os
from neptunelib import Session

session = Session(api_token=os.environ['NEPTUNE_API_TOKEN'])

```

**Comment by pitercl** [comment]
This changes the semantics a bit: the `NEPTUNE_API_TOKEN` needs to be present at the time of importing the lib (it would actually need to be `=os.environ.get('NEPTUNE_API_TOKEN')`)

If you feel this simplification is worth the less elastic semantics, I'm ok with it.

**Comment by jakubczakon** [comment]
@pitercl I seems that if I have the `Session.__init__` like this:

```python
def __init__(self, api_token=None):
   credentials = Credentials(api_token) if api_token else Credentials.from_env()
   self.credentials = credentials 
   self._client = Client(self.credentials.api_address, self.credentials.api_token)
```

it works with no problems. 

Could you please elaborate on the problems you mentioned?

**Comment by pitercl** [comment]
I'm ok with this implementation. The problem I mentioned would only appear if the implementation would be
```py
class Session(object):
    def __init__(self, api_token=os.environ['NEPTUNE_API_TOKEN']):
         ...
```

Sorry if I misunderstood your initial comment.

**Comment by jakubczakon** [comment]
Done in #25
