### ISSUE TITLE
Public projects are not available.

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ml/neptune-lib#5]
Public projects are not available to the user.

Running:

```python
projects.get_projects('USERNAME')
```

Shows only the private/public projects of the user but all public projects should be visible.

**Comment by pitercl** [comment]
This is the semantics of this method as we planned it. I don't think we should list all public project available in Neptune here.

The idea here is to allow user to access projects she wants to access, not browse available projects (that's more of a UI feature).

**Comment by kamil-kaczmarek** [comment]
@jakubczakon Are you unable to access any public project that you participated in? If so, we will need to figure out solution to that.

**Comment by jakubczakon** [comment]
@kamil-kaczmarek as a random user I would like to be able to access `neptune-ml/Salt-Detection` for example and I was under the impression that I may not be able to do that. 
I will try and check it somehow and get back to you if I couldn't or drop the issue if I could.

**Comment by pitercl** [comment]
You should absolutely be able to do that:
```
Session(..).get_projects('neptune-ml')['neptune-ml/Salt-Detection']
```
